"""v_03_change_foreigh_key

Revision ID: 2c75d3bff64a
Revises: e3b0d6d973af
Create Date: 2024-06-03 18:13:33.926936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c75d3bff64a'
down_revision: Union[str, None] = 'e3b0d6d973af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('thread_model_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'emails', 'threads', ['thread_model_id'], ['id'])
    op.drop_constraint('threads_email_id_fkey', 'threads', type_='foreignkey')
    op.drop_column('threads', 'email_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threads', sa.Column('email_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('threads_email_id_fkey', 'threads', 'emails', ['email_id'], ['id'])
    op.drop_constraint(None, 'emails', type_='foreignkey')
    op.drop_column('emails', 'thread_model_id')
    # ### end Alembic commands ###
