"""V_01_create_email_and_thread_tablesclear

Revision ID: e3b0d6d973af
Revises: 93e08ddd6676
Create Date: 2024-05-31 12:14:04.482699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3b0d6d973af'
down_revision: Union[str, None] = '93e08ddd6676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
